# SERVER ??
server:
  port: 9091
  servlet:
    context-path: /api
  error:
    path: /error
    whitelabel:
      enabled: false
  shutdown: graceful
  tomcat:
    accesslog:
      enabled: true
      max-days: 14
      pattern: '%{yyyy-MM-dd HH:mm:ss}t\t%s\t%r\t%{User-Agent}i\t%{Referer}i\t%a\t%b'
      rotate: true
    basedir: .

# SPRING ??
spring:
  web:
    locale: ko_KR
    resources:
      add-mappings: false
  messages:
    basename: message/messages
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
    group:
      local: profiles-local
        , logging-type-console
        , logging-level-local
        , main_db_single
      dev: profiles-dev
        , logging-type-console
        , logging-level-dev
        , main_db_replication

---
# LOCAL ??
spring.config.activate.on-profile: "profiles-local"
spring:
  config:
    import:
      classpath:config/datasource/datasource-local.yml,
      classpath:config/environment/environment-local.yml


---
# DEV ??
spring.config.activate.on-profile: "profiles-dev"
spring:
  config:
    import:
      classpath:config/datasource/datasource-dev.yml,
      classpath:config/environment/environment-dev.yml
